var Message = {
  GAME : 'GAME',
  CREATE: 'CREATE',
  JOIN: 'JOIN',
  ROOMID: 'ROOMID',
  READY: 'READY',
  START: 'START',
  ERROR : 'ERROR',
  INFO : 'INFO',
  
  CHARACTER: 'CHARACTER',
	EXTRA: 'EXTRA',
	NEXT: 'NEXT',
	WOLF_ROUND: 'WOLF_ROUND',
	WITCH_ROUND: 'WITCH_ROUND',
	SEER_ROUND: 'SEER_ROUND',
	SAVIOR_ROUND: 'SAVIOR_ROUND',
	HUNTER_ROUND: 'HUNTER_ROUND',
	ROUND_END: 'R_END',


	ENABLE_HOST: 'ENABLE_HOST',
	INDEX: 'INDEX',
	SIZE: 'SIZE',

  PLAYERINDEX: 'PLAYERINDEX',
  LISTREQUEST : 'LISTREQUEST',
  REPORT : 'REPORT',
  RESEND : 'RESEND',
  GAMENAME : 'GAMENAME',

}

var Game = {
	WOLF: 'WOLF',
	SEER: 'SEER',
	WITCH: 'WITCH',
	HUNTER: 'HUNTER',
	SAVIOR: 'SAVIOR',
	IDIOT: 'IDIOT',
	TOWNFOLK: 'TOWNFOLK',
	WHITE_WOLF: 'WHITE_WOLF',
	SISTER: 'SISTER',
	KILL: 'KILL',
	INDEX: 'INDEX',
	WITCH_SAVE: 'W_SAVE',
	WITCH_KILL: 'W_KILL',
	SAVIOR_SAVE: 'SAVIOR_SAVE',
}

if (typeof(exports) !== 'undefined' && exports != null) {
  exports.Message = Message;
  exports.Game = Game;
}